node {
  stage 'build app'
  openshiftBuild(namespace: 'labs-ci-cd', buildConfig: 'welcome', showBuildLogs: 'true')
  stage 'execute image scan'
    openshift.withCluster() {
	def models = openshift.process( "labs-ci-cd//image-inspector-template", "-p", "APPLICATION_NAME=image-inspector", "-p", "IMAGE_URL=172.30.1.1:5000/labs-ci-cd/welcome:latest")
        echo "Creating this template will instantiate ${models.size()} objects"
        def created = openshift.create( models )
        echo "Application created"
    }
  stage 'review report'
  input "Do you want to deploy the application ?"

  stage 'deploy app'
  openshiftDeploy(namespace: 'labs-demo', deploymentConfig: 'welcome')
}
